### ISSUE TITLE
Nord is currently unavailable through package install

### ISSUE THREAD

**Issue by spencergilbert** [arcticicestudio/nord-sublime-text#15]
[Package link](https://packagecontrol.io/packages/Nord)

![image](https://user-images.githubusercontent.com/11903873/39578642-b5f0673e-4eb2-11e8-8de9-48555f6732d5.png)

Confirmed that it also isn't available through the package install command in sublime text

**Comment by arcticicestudio** [comment]
The package is still in development and hasn't been pushed to the registry yet. The plan was to wait until the [UI part has been done](https://github.com/arcticicestudio/nord-sublime-text/issues/6) to provide both with the same version, but given the fact that many user opened issues for this I'll go ahead this weekend and release the initial version only including the syntax theme for the time being.

**Comment by arcticicestudio** [comment]
Duplicate of #7

**Comment by spencergilbert** [comment]
Whoops, sorry - didn't see that closed ticket!

**Comment by arcticicestudio** [comment]
No problem, as you can see in the ticket timeline there are several other issues linked to it :smile: 
I can understand that the current documentation in the README is a bit confusing since I have wrote it in advance for the first release version, but I did not expect the Sublime Text UI Theming API to be such a bad system (see #6 ).
