### ISSUE TITLE
No release available for manual install

### ISSUE THREAD

**Issue by celmfire** [arcticicestudio/nord-sublime-text#16]
Trying to download and install the package, but it's not available either via package manager (Issue #7  I assume) or via direct download. Has it been removed for some reason?

**Comment by dimitrisnl** [comment]
@arcticicestudio Any updates on this?

**Comment by arcticicestudio** [comment]
@Elmfire @dimitrisnl Sorry for the delay, I've actually no free time (job, study, life etc.) to work on my or any other OSS project, please see [Tweet from April][t-april] and [Tweet from June][t-june].

Like @Elmfire already mentioned this is related to #7.

There is indeed no release yet, but you can install it manually by following the _Manual_ install instructions in the README, but clone the `develop` branch into the created directory instead of downloading the `.zip` release archive file. The branch currently contains the syntax theme, the [UI theme is still in development][gh-6].

[t-april]: https://twitter.com/arcticicestudio/status/987753414342914049
[t-june]: https://twitter.com/arcticicestudio/status/1004777280646844417
[gh-6]: https://github.com/arcticicestudio/nord-sublime-text/issues/6

**Comment by gusbemacbe** [comment]
@arcticicestudio 

You are closed to contributors while you are busy. Too bad you refuse to have contributors when you are away. I drop totally Nord themes for other themes developed by the active community. Better using themes developed by an active community over those developed by an inactive individual.

**Comment by arcticicestudio** [comment]
@gusbemacbe I think this is off-topic and not the correct channel, but I'd like to give some feedback anyway. Get ready for a wall of text, you did not want it otherwise :smile:

> [...] developed by an **inactive individual**.

Outwardly, it might look like I'm inactive, but I work hard to release a first public alpha of the new [Nord Docs][nd] which includes a brand new website and the official documentations for Nord itself and all of its port projects. There is a [design concept][dc] issue if you want to know more details about it. I currently spent all my available coding free time on it to get it out as fast as possible. Getting this done will help to reduce the maintaining costs by almost 100% so I can finally work off all the accumulated issues all over the repositories.
Anyway, my day starts at 5:00 AM and I'm usually not home before 9:00 PM. This includes my job as software developer and all the other “real life” things (sport activities, volunteer work, spent time with friends etc.). Between all of these things, I try to contribute to multiple OSS projects and maintain my own ones.

> You are **closed to contributors** while you are busy.
> Too bad you **refuse to have contributors** [...]

Sorry, but I must absolutely contradict this statements! **I appreciate every help, no matter in what form, and I'm thankful for every contributor**.
The thing is many times users report problems, but don't follow the contribution guidelines. I've too few information and details about the problem, no way to reproduce it or I have to guess the steps to go.
Also there are only rarely users who submit a PR to resolve the reported issue. This is absolutely no problem because nobody can expect that users know about the code or the programming language of the project, they just want to use it. Adding multiple contributors to the repository and grant them the permission to approve PRs would only make the process slightly faster, because call me „control addicted“ or whatever, but I'd like to reproduce and test changes on my own before merging things in blindly. It is not meant to be evil, but there are users that try to merge in their personal preferences into the code instead of thinking in a general way of use so the projects would sooner or later end up in a bunch of spaghetti code.
However, all these facts drastically increase the time to resolve a issue which then results in a back pressure of the issues in the queue.

Regarding your statement about the need to use a “theme developed by an active community“: There is a really active community around Nord. Unfortunately due to a currently missing uniform way of communication it's not easy to find and join it :disappointed:
But that's the reason I work hard on the website to finally resolve this problem as described in the design concept issue. Besides, I don't know either which of my port projects (or any other color theme/scheme based project out there) requires to be updated like once a week to be usable. To be honest, in the end these projects are just color themes/schemes which in most cases are finished after the first version has been pushed. There are some apps like Atom, Vim or VS Code that constantly extend the functionality of their color theme APIs, but most port projects like the terminal emulator themes are there to stay forever.

In the end you're free to choose whatever theme you like to fullfill your needs, that's the reason why color themes exist and not only one :wink:
If there is a problem that prevents you from using any of the projects anymore let me know so we can see how to solve it.

Back to topic regarding this issue: If you feel like manual installation instructions are an absolute blocker for this project feel free to submit a PR because like I mentioned above I warmly welcome every helper. PRs related to documentations are also predestined to be merged fast because there's no need to reproduce them in any way.

[nd]: https://github.com/arcticicestudio/nord-docs
[dc]: https://github.com/arcticicestudio/nord-docs/issues/1

**Comment by roycyt** [comment]
Actually we can configure the package control manager to let it find the `nord-sublime-text` package.
Just add following lines to the `Package Control.sublime-settings` file:
```
"repositories":
[
    "https://github.com/arcticicestudio/nord-sublime-text/tree/develop"
]
```

**Comment by mitinarseny** [comment]
@roycyt 
How to install theme after adding those lines?

**Comment by roycyt** [comment]
@mitinarseny 
Just like the usual way to install a package in the Sublime Text.
Trigger the `Command Palette`, then `Package Control: Install Package`. Select the `nord-sublime-text` package.

**Comment by mitinarseny** [comment]
@roycyt I've tried this, but there was no new theme after it. 
<img width="637" alt="image" src="https://user-images.githubusercontent.com/10659110/59146048-08d9e000-89f5-11e9-8921-66b78fd61648.png">
Maybe the problem is in the theme format `.tmTheme`? I've also tried to convert it to `.sublime-color-scheme`, but it doesn't help...(

**Comment by roycyt** [comment]
@mitinarseny 

This is what I get:
![screenshot](https://user-images.githubusercontent.com/3922108/59149541-d3f77880-8a48-11e9-82aa-05c879c60f50.png)

**Comment by mitinarseny** [comment]
@roycyt I've already done installation of that plugin. Now it is time to apply installed theme to sublime. But I have absolutely no idea how to do that( Can you help with that, please?

**Comment by roycyt** [comment]
@mitinarseny 
Trigger the Command Palette, type "UI: Select Color Scheme".

**Comment by mitinarseny** [comment]
@roycyt [This](https://github.com/arcticicestudio/nord-sublime-text/issues/16#issuecomment-500115233) screenshot was about it

**Comment by arcticicestudio** [comment]
The initial package version [0.1.0][] has finally been released and deployed to the _Package Control_ registry through https://github.com/wbond/package_control_channel/pull/7652 :tada: 
The PR is still pending, but the automatic tests already passed successfully and it should be reviewed quickly.

:arrow_right: The theme will be available as new package named :snowflake: [Nord][pc].

The project also migrated like all other ports to the [new and shiny website][web] for a clean appearance and code base and a way simpler maintenance and development workflow.

[0.1.0]: https://github.com/arcticicestudio/nord-sublime-text/releases/tag/v0.1.0
[web]: https://www.nordtheme.com/ports/sublime-text
[pc]: https://packagecontrol.io/packages/Nord
