### ISSUE TITLE
Images in README dont load

### ISSUE THREAD

**Issue by prog1dev** [arcticicestudio/nord-sublime-text#8]
Images in sections [Features](https://github.com/arcticicestudio/nord-sublime-text/blob/develop/README.md#features), [Package Support](https://github.com/arcticicestudio/nord-sublime-text/blob/develop/README.md#package-support) and [Languages](https://github.com/arcticicestudio/nord-sublime-text/blob/develop/README.md#languages) dont load. 

Errors in console:
```
Refused to load the image 'https://raw.githubusercontent.com/arcticicestudio/nord-sublime-text/develop/assets/scrot-lang-yaml.png' because it violates the following Content Security Policy directive: "img-src 'self' data: assets-cdn.github.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com collector.githubapp.com avatars0.githubusercontent.com avatars1.githubusercontent.com avatars2.githubusercontent.com avatars3.githubusercontent.com github-cloud.s3.amazonaws.com".
```

```
Failed to load resource: https://github.com/arcticicestudio/nord-sublime-text/raw/develop The server responded with a status of 404 (Not Found)
```

Browsers: Chrome 63.0.3239.132, Safari 11.0.2 (13604.4.7.1.6)

**Comment by lee-hyunkyu** [comment]
FWIW, currently running Safari 11.0.1 (12604.3.5.1.1) and I'm not having any issues.

**Comment by arcticicestudio** [comment]
Such problems are not related to the project / repository. The SVG files are loaded through [RawGit][rg]. GitHub doesn't render SVG's due to security reasons. All other images like screenshots (PNG) should work just fine. The only image that might through an error is the shield  / badge of the Circle CI build because the project is not configured yet and the build currently does not exist.

@prog1dev Please make sure to allow RawGit in your ad blocker browser plugin / addon which probably blocks RawGit or generally some GitHub assets server.

[rg]: https://rawgit.com

**Comment by prog1dev** [comment]
yea, this one is on my side
thanks
